foobar : main.o add.o sub.o div.o mul.o
	gcc -o foobar main.o add.o sub.o div.o mul.o

main.o : main.c
	gcc -c main.c

add.o : add.c
	gcc -c add.c

sub.o : sub.c
	gcc -c sub.c

div.o : div.c
	gcc -c div.c

mul.o : mul.c
	gcc -c mul.c
